languageCode = 'en-us'
title = "ezntek's blog"
theme = "fuji"
baseurl = "/"

[permalinks]
	post = "/posts/:year/:month/:title/"

[params]
	author = "ezntek"
	description = "A 14-year-old asian programmer."
	subTitle = "ezntek's Site."
	sourceURL = "https://github.com/ezntek/ezntek.github.io"
	showLicense = true
	license = "the Creative Commons BY-NC-SA 4.0 License"
	licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"
	#avatar = ""

	contentTypeName = "posts"
	showMenuItems = 3
	showLanguageSelector = false
	fullWidthTheme = true
	centerTheme = true
	# favicon = "favicon.ico"
	showLastUpdated = true
	enableGitInfo = true
	updatedDatePrefix = "Updated"
	paginate = 50

[markup.goldmark.renderer]
	unsafe = true
		

[authors]
	[[authors.ezntek]]
		name = "ezntek"
		default = true	

[languages]
	[languages.en]
		languageName = "English"
		title = "ezntek's Site"
		subtitle = "My personal site."
		owner = "ezntek"
		keywords = ""
		copyright = "Eason Qin 2023"
		menuMore = "Show More"
		readMore = "Read More"
		readOtherPosts = "Read other posts"
		missingContentMessage = "Page not found..."
		missingBackButtonLabel = "Back to home"
		
		[languages.en.params.logo]
			logoText = "ezntek's Blog."
			logoHomeLink = "/"

		[languages.en.menu]
			[[languages.en.menu.nav]]
				name = "Home"
				url = "/"
				weight = 10
			[[languages.en.menu.nav]]
				name = "About"
				url = "/about"
				weight = 20
			[[languages.en.menu.nav]]
				name = "My Stuff"
				url = "/stuff"
				weight = 30
			#[[languages.en.menu.nav]]
			#	pre = ""
			#	identifier = "blog"
			#	name = "Blog"
			#	url = "/posts"
			#	weight = 40
			
			# links
			[[languages.en.menu.link]]
				url = "https://github.com/ezntek"
				name = "GitHub" # GitHub
			
			

