languageCode = 'en-us'
title = "ezntek's blog"
theme = "PaperMod"
baseurl = "/"

[permalinks]
	post = "/posts/:year/:month/:title/"

[params]
	author = "ezntek"
	description = "A 14-year-old asian programmer."
	subTitle = "ezntek's Site."
	sourceURL = "https://github.com/ezntek/ezntek.github.io"
	showLicense = true
	license = "the Creative Commons BY-NC-SA 4.0 License"
	licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"
	#avatar = ""

	contentTypeName = "posts"
	showMenuItems = 3
	showLanguageSelector = false
	fullWidthTheme = true
	centerTheme = true
	# favicon = "favicon.ico"
	showLastUpdated = true
	enableGitInfo = true
	updatedDatePrefix = "Updated"
	paginate = 50
	ShowBreadCrumbs = true
	ShowReadingTime = true

	[params.homeInfoParams]
	Title = "Hey, Welcome! 👋"
	Content = "<strong>Introductions first: </strong>I'm Eason (aka ezntek), a 14-year-old Asian programmer living in 🇸🇬, and this is where I post semi-personal content in the form of a blog."

	[[params.socialIcons]]
	name = "github"
	url = "https://github.com/ezntek"

	[[params.socialIcons]]
	name = "email"
	url = "mailto:ezntek@xflymusic.com"

	[[params.socialIcons]]
	name = "reddit"
	url = 'https://reddit.com/u/EasonTek2398'

	[[params.socialIcons]]
	name = "matrix"
	url = "https://matrix.to/#/@eazonteck:matrix.org"


[markup.goldmark.renderer]
	unsafe = true
		

[authors]
	[[authors.ezntek]]
		name = "ezntek"
		default = true	

[languages]
	[languages.en]
		languageName = "English"
		title = "ezntek"
		subtitle = "My personal site."
		owner = "ezntek"
		keywords = ""
		copyright = "Eason Qin 2023 - Present."
		menuMore = "Show More"
		readMore = "Read More"
		readOtherPosts = "Read other posts"
		missingContentMessage = "Page not found..."
		missingBackButtonLabel = "Back to home"
		
		[languages.en.params.logo]
			logoText = "ezntek's Blog."
			logoHomeLink = "/"

		[languages.en.menu]
			[[languages.en.menu.main]]
				name = "Home"
				url = "/"
				weight = 10
			[[languages.en.menu.main]]
				name = "About"
				url = "/about"
				weight = 20
			[[languages.en.menu.main]]
				name = "My Stuff"
				url = "/stuff"
				weight = 40
			[[languages.en.menu.main]]
				identifier = "blog"
				name = "Blog"
				url = "/posts"
				weight = 30
			[[languages.en.menu.main]]
				identifier = "tags"
				url = "/tags"
				name = "Tags"
				weight=50
			
			# links
			[[languages.en.menu.link]]
				url = "https://github.com/ezntek"
				name = "GitHub" # GitHub
			