languageCode = 'en-us'
title = "ezntek's blog"
theme = "PaperMod"
baseurl = "/"

[permalinks]
	post = "/posts/:year/:month/:title/"

[params]
	author = "ezntek"
	description = "A 16-year-old asian programmer."
	subTitle = "ezntek's Site."
	sourceURL = "https://github.com/ezntek/ezntek.github.io"
	showLicense = true
	license = "the Creative Commons BY-NC-SA 4.0 License"
	licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"
	#avatar = ""
        showFullTextinRSS = true

	contentTypeName = "posts"
	showMenuItems = 3
	showLanguageSelector = false
	fullWidthTheme = true
	centerTheme = true
	# favicon = "favicon.ico"
	showLastUpdated = true
	enableGitInfo = true
	updatedDatePrefix = "Updated"
	paginate = 50
	ShowBreadCrumbs = false
	ShowReadingTime = true

	[params.homeInfoParams]
	Title = "Hey, Welcome! 👋"
	Content = "<strong>Introductions first: </strong>I'm Eason (aka ezntek), a 16-year-old Asian programmer living in 🇸🇬, and this is where I post semi-personal content in the form of a blog."

	[[params.social.socialIcons]]
	name = "github"
	url = "https://github.com/ezntek"

	[[params.social.socialIcons]]
	name = "email"
	url = "mailto:eason@ezntek.com"

	[[params.social.socialIcons]]
	name = "reddit"
	url = 'https://reddit.com/u/EasonTek2398'

        [[params.social.socialIcons]]
        name = "rss"
        url = "index.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
	unsafe = true
		

[authors]
	[[authors.ezntek]]
		name = "ezntek"
		default = true	

[languages]
	[languages.en]
                [languages.en.params]
                    languageName = "English"
                    title = "ezntek"
                    subtitle = "My personal site."
                    owner = "ezntek"
                    copyright = "Eason Qin 2023 - Present."
                    menuMore = "Show More"
                    readMore = "Read More"
                    readOtherPosts = "Read other posts"
                    missingContentMessage = "Page not found..."
                    missingBackButtonLabel = "Back to home"
		
		[languages.en.params.logo]
			logoText = "ezntek's Blog."
			logoHomeLink = "/"

		[languages.en.menu]
			[[languages.en.menu.main]]
				name = "home"
				url = "/"
				weight = 10
			[[languages.en.menu.main]]
				name = "about"
				url = "/about"
				weight = 20
                        [[languages.en.menu.main]]
                                name = "revision"
                                url = "/revision"
                                weight = 30
			[[languages.en.menu.main]]
				identifier = "blog"
				name = "blog"
				url = "/posts"
				weight = 40
			[[languages.en.menu.main]]
				name = "my stuff"
				url = "/stuff"
				weight = 50 
			[[languages.en.menu.main]]
				identifier = "tags"
				url = "/tags"
				name = "tags"
				weight = 70
			
			# links
			[[languages.en.menu.link]]
				url = "https://github.com/ezntek"
				name = "GitHub" # GitHub
			
