languageCode = 'en-us'
title = "ezntek's blog"
baseurl = "/"

[params]
	contentTypeName = "posts"
	showMenuItems = 3
	showLanguageSelector = false
	fullWidthTheme = true
	centerTheme = true
	# favicon = "favicon.ico"
	showLastUpdated = true
	enableGitInfo = true
	updatedDatePrefix = "Updated"

[languages]
	[languages.en]
		languageName = "English"
		title = "Ezntek's blog"
		subtitle = "My personal blog."
		owner = ""
		keywords = ""
		copyright = ""
		menuMore = "Show More"
		readMore = "Read More"
		readOtherPosts = "Read other posts"
		missingContentMessage = "Page not found..."
		missingBackButtonLabel = "Back to home"
		
		[languages.en.params.logo]
			logoText = "test logo text"
			logoHomeLink = "/"

		[languages.en.menu]
			[[languages.en.menu.main]]
			identifier = "about"
			name = "About"
			url = "/about"
			[[languages.en.menu.main]]
			identifier = "stuff"
			name = "My Stuff"
			url = "/stuff"

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"